Repository Labs-EU4/lambda-door-client, pull requests merged in 2020-02, with the labels that each got.

#4 Hover and round corners
  src/App.css
  src/components/Company/CompanyReview/CompanyReviewCard.jsx
  src/components/Company/InterviewReviews/InterviewReviewList.jsx
  src/components/Company/SalaryReviews/SalaryReviewsList.jsx
  src/components/CompanySummaryCard.jsx
  src/components/Layout/Search/CompanySearchCard.jsx
  src/components/Layout/Search/InterviewSearchCard.jsx
  src/components/Layout/Search/SalarySearchCard.jsx
  src/components/MyReviews/Company/SmallReviewCard.jsx
  src/components/MyReviews/Interview/SmallReviewCard.jsx
  src/components/MyReviews/Salary/SmallSalaryReviewCard.jsx
  src/components/UserDashboard/TopRated/TopRatedList.jsx
  src/components/UserDashboard/UserLocationComp/ClosestLocationList.jsx
Labels: bug, enhancement

#7 fixed ratings
  src/components/CompanySummaryCard.jsx
Labels: bug

#8 component created
  src/components/Router/index.jsx
  src/components/UserDashboard/TopRated/HighestRated.jsx
  src/components/UserDashboard/TopRated/TopRatedList.jsx
  src/pages/UserDashboard/UserDashboard.jsx
Labels: enhancement
